/*
 * NacaRTTests - Naca Tests for NacaRT support.
 *
 * Copyright (c) 2005, 2006, 2007, 2008 Publicitas SA.
 * Licensed under GPL (GPL-LICENSE.txt) license.
 */
package parser;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import lexer.CTokenList;





/*
            builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();
            doc = builder.newDocument();
            Element elem = doc.createElement("SMS");
            elem.setAttribute("Message", csMessage);
            elem.setAttribute("Originator", csMSISDN);
            elem.setAttribute("Destinator", csShortID);
            doc.appendChild(elem);

 */


/**
 * @author U930CV
 *
 */
public abstract class CParser<T extends CBaseElement>
{
    public CGlobalCommentContainer commentContainer = new CGlobalCommentContainer() ;

    // entry point for parsing
    // get a CTokenList as input, this object is generated by CLexer
    /** Executes the start parsing operation. */
    public boolean StartParsing(CTokenList lstTokens)
    {
        if (lstTokens == null || lstTokens.GetNbTokens()==0)
        {
            return false ;
        }

        // start parsing
        lstTokens.StartIter() ;
        return DoParsing(lstTokens) ;
    }

    protected abstract boolean DoParsing(CTokenList lstTokens) ;

    /** Executes the get root element operation. */
    public T GetRootElement()
    {
        return eRoot ;
    }

    /** Executes the export operation. */
    public Document Export()
    {
        if (eRoot == null)
        {
            return null ;
        }
        // init members
        try
        {
            DocumentBuilder builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();
            Document doc = builder.newDocument();
            Element eProgram = eRoot.Export(doc) ;
            doc.appendChild(eProgram) ;
            return doc ;
        }
        catch (ParserConfigurationException e)
        {
            return null ;
        }
//      catch (NullPointerException e)
//      {
//          Transcoder.logError("Errors found: Could not generate output");
//          return null;
//      }
    }

    protected T eRoot = null ;

    public void setRoot(T tRoot)
    {
        eRoot = tRoot;
    }

    /** Executes the clear operation. */
    public void Clear()
    {
        commentContainer.Clear();
        eRoot.Clear();
    }
}
