spring:
  application:
    name: naca-cloud-native
  flyway:
    enabled: false

carddemo:
  enabled: false

server:
  port: 8000

logging:
  level:
    root: INFO
    com.publicitas.naca.cloudnative: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
